service:
  name: naamapi

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  cacheBucket: naamapi-${self:custom.stage}-cache-bucket

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  profile: naamapi-admin
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  vpc: ${file(./config.yml):vpc}

  environment:
    stage: ${self:custom.stage}
    region: ${self:custom.region}
    cacheBucket: ${self:custom.cacheBucket}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.cacheBucket}/*"

functions:
  mainPage:
    handler: src/functions/content.mainInfoPages
    events:
      - http:
          method: get
          path: main-pages/
  cache:
    handler: src/functions/cache.handler
    events:
      - http:
          method: get
          path: cache/
      - http:
          method: post # Sets the cache, used by Contentful
          path: cache/

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.cacheBucket}
  Outputs:
     NewOutput:
       Description: "Bucket for caching"
       Value: "Some output value"

