service:
  name: naamapi

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  assetsBucket: naamapi-${self:custom.stage}-assets

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  profile: naamapi-admin
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  vpc: ${file(./config.yml):vpc}

  environment:
    STAGE: ${self:custom.stage}
    REGION: ${self:custom.region}
    ASSETS_BUCKET: ${self:custom.assetsBucket}
    ONESIGNAL_S3_FILENAME: 'notifications.json'
    CACHE_FILE_NAME: 'cache-time.json'

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "arn:aws:s3:::${self:custom.assetsBucket}/*"

functions:
  sandbox:
    handler: src/functions/sandbox.handler
    events:
      - http:
          method: get
          path: sandbox

  dynamicContent:
    handler: src/functions/dynamic-content.handler
    events:
      - http:
          method: get
          path: dynamic-content/{contentTypes}
      - http:
          method: get
          path: dynamic-content/

  cache:
    handler: src/functions/cache.handler
    events:
      - http:
          method: get
          path: cache/
      - http:
          method: post # Sets the cache, used by Contentful
          path: cache/

  notifications:
    handler: src/functions/notifications.handler
    events:
      - http:
          method: get
          path: notifications/

  scheduledNotifications:
    handler: src/functions/notifications.scheduleHandler
    events:
      - schedule: rate(15 minutes)

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.assetsBucket}
  Outputs:
     NewOutput:
       Description: "Bucket for caching"
       Value: "Some output value"

