service:
  name: naamapi

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  profile: naamapi-admin

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${self:custom.stage}
  region: ${self:custom.region}
  vpc: ${file(./config.yml):vpc}

  environment:
    stage: ${self:custom.stage}
    region: ${self:custom.region}

functions:
  mainPage:
    handler: src/functions/content.mainPage
    events:
      - http:
          method: get
          path: main-page/{pageName}

